version: '2'
services:

  database:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - db:/var/lib/mysql

  api:
    depends_on:
      - database
    restart: on-failure
    env_file:
      - .env
    container_name: api-server
    build:
      context: api-build-context
      dockerfile: Dockerfile
    ports:
      - $APP_PORT:$APP_PORT
    environment: 
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://database:$MYSQL_PORT/$MYSQL_DATABASE?useSSL=false",
        "spring.datasource.username":"$MYSQL_USERNAME",
        "spring.datasource.password":"$MYSQL_PASSWORD"
      }'

volumes:
  db: